spring.application.name=coffee-brewing-calculator

# for dev boot actuator
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=Coffee Brewing Calculator
info.app.description=A Spring Boot app I use to work out my coffee measurements.
info.app.version=1.0.0
